index:
    path: /
    controller: App\Controller\TweetController::index

api_index:
  path: /api
  controller: App\Controller\ApiController::index
  methods: ["GET"]

ver_tweet:
    path: /tweet/{id}
    controller: App\Controller\TweetController::verTweet

api_get_tweet:
  path: /api/tweets/{id}
  controller: App\Controller\ApiController::getTweet
  methods: ["GET"]

api_get_tweets:
  path: /api/tweets/
  controller: App\Controller\ApiController::getTweets
  methods: ["GET"]  

api_get_user:
  path: /api/users/{id}
  controller: App\Controller\ApiController::getTweetfonyUser
  methods: ["GET"]    

api_get_users:
  path: /api/users/
  controller: App\Controller\ApiController::getTweetfonyUsers
  methods: ["GET"]      

# POST

api_post_user:
  path: /api/users
  controller: App\Controller\ApiController::postTweetfonyUser
  methods: ["POST"]

api_post_tweet:
  path: /api/tweets
  controller: App\Controller\ApiController::postTweet
  methods: ["POST"]

